export const CARD_WIDTH = 68;
export const CARD_HEIGHT = 86;

export const SUIT_SPADES = 'S';
export const SUIT_HEARTS = 'H';
export const SUIT_DIAMONDS = 'D';
export const SUIT_CLUBS = 'C';
export const SUITS = [SUIT_SPADES, SUIT_HEARTS, SUIT_DIAMONDS, SUIT_CLUBS];
export const SUIT_NONE = 'NONE';

export const SUIT_BLACK = 'black';
export const SUIT_RED = 'red';

export const INDEX_SUIT_SPADES = 0;
export const INDEX_SUIT_HEARTS = 1;
export const INDEX_SUIT_DIAMONDS = 2;
export const INDEX_SUIT_CLUBS = 3;

export const NUMBER_A = 1;
export const NUMBER_2 = 2;
export const NUMBER_3 = 3;
export const NUMBER_4 = 4;
export const NUMBER_5 = 5;
export const NUMBER_6 = 6;
export const NUMBER_7 = 7;
export const NUMBER_8 = 8;
export const NUMBER_9 = 9;
export const NUMBER_10 = 10;
export const NUMBER_J = 11;
export const NUMBER_Q = 12;
export const NUMBER_K = 13;
export const NUMBERS = [
  NUMBER_A,
  NUMBER_2,
  NUMBER_3,
  NUMBER_4,
  NUMBER_5,
  NUMBER_6,
  NUMBER_7,
  NUMBER_8,
  NUMBER_9,
  NUMBER_10,
  NUMBER_J,
  NUMBER_Q,
  NUMBER_K,
];
export const NUMBERS_SORTED = [
  NUMBER_A,
  NUMBER_K,
  NUMBER_Q,
  NUMBER_J,
  NUMBER_10,
  NUMBER_9,
  NUMBER_8,
  NUMBER_7,
  NUMBER_6,
  NUMBER_5,
  NUMBER_4,
  NUMBER_3,
  NUMBER_2,
];
export const NUMBER_NONE = -1;

export const CARD_NONE = { suit: SUIT_NONE, number: NUMBER_NONE };

export const PERSON_1 = 'PERSON 1';
export const PERSON_2 = 'PERSON 2';
export const PERSON_3 = 'PERSON 3';
export const PERSON_4 = 'PERSON 4';

export const HAND_TYPE_STRAIGHT_FLUSH = 9;
export const HAND_TYPE_FOUR_OF_A_KIND = 8;
export const HAND_TYPE_FULL_HOUSE = 7;
export const HAND_TYPE_FLUSH = 6;
export const HAND_TYPE_STRAIGHT = 5;
export const HAND_TYPE_THREE_OF_A_KIND = 4;
export const HAND_TYPE_TWO_PAIR = 3;
export const HAND_TYPE_PAIR = 2;
export const HAND_TYPE_HIGH_CARD = 1;

export const SOLUTION_OPTIONS_STATE_OK = 'OK';
export const SOLUTION_OPTIONS_STATE_INVALID = 'INVALID';
export const SOLUTION_OPTIONS_STATE_DONE = 'DONE';

// note: THREE_OF_A_KIND hints also apply to the three of a kind of a full house, as they are three cards of the same number in the same location
// note: PAIR hints also apply to the pair in a full house and to two pairs
export const HINT_NUMBER_NOT_USED = 'NUMBER NOT USED';
export const HINT_STRAIGHT_NUMBER_KNOWN = 'STRAIGHT NUMBER KNOWN';
export const HINT_NO_STRAIGHT_FLUSH_IN_SUIT = 'NO STRAIGHT FLUSH IN SUIT';
export const HINT_NO_STRAIGHT_FLUSH_IN_NUMBER = 'NO STRAIGHT FLUSH IN NUMBER';
export const HINT_NO_STRAIGHT_IN_NUMBER = 'NO STRAIGHT IN NUMBER';
export const HINT_SAME_COUNT_LEFT_SUIT = 'HINT SAME COUNT LEFT SUIT';
export const HINT_SAME_COUNT_LEFT_NUMBER = 'HINT SAME COUNT LEFT NUMBER';
export const HINT_FOUR_OF_A_KIND_SUIT = 'FOUR OF A KIND SUIT';
export const HINT_FOUR_OF_A_KIND_NUMBERS = 'FOUR OF A KIND NUMBERS';
export const HINT_PLACED_CARD_REMOVE_SUIT = 'PLACED CARD REMOVE SUIT';
export const HINT_PLACED_CARD_REMOVE_NUMBER = 'PLACED CARD REMOVE NUMBER';
export const HINT_NUMBER_USED_UP = 'NUMBER USED UP';
export const HINT_ALL_OF_SUIT_PLACED = 'ALL OF SUIT PLACED';
export const HINT_ALL_OF_SUIT_PLACED_NUMBERS = 'ALL OF SUIT PLACED NUMBERS';
export const HINT_ALL_OF_NUMBER_PLACED = 'ALL OF NUMBER PLACED';
export const HINT_ALL_OF_NUMBER_PLACED_SUITS = 'ALL OF NUMBER PLACED SUITS';
export const HINT_THREE_OF_A_KIND_NUMBERS = 'THREE OF A KIND NUMBERS';
export const HINT_THREE_OF_A_KIND_SUITS = 'THREE OF A KIND SUITS';
export const HINT_PAIR_NUMBERS = 'PAIR NUMBERS';
export const HINT_PAIR_SUITS = 'PAIR SUITS';
export const HINT_CLUE_SUIT_AND_NUMBER = 'CLUE SUIT AND NUMBER';
export const HINT_CLUE_SUIT = 'CLUE SUIT';
export const HINT_CLUE_NOT_SUIT = 'CLUE NOT SUIT';
export const HINT_CLUE_NUMBER = 'CLUE NUMBER';
export const HINT_CLUE_NOT_NUMBER = 'CLUE NOT NUMBER';
export const HINT_CLUE_CARDS_SAME_NUMBER = 'CLUE CARDS SAME NUMBER';
export const HINT_CLUE_CARDS_NOT_SAME_NUMBER = 'CLUE CARDS NOT SAME NUMBER';
export const HINT_CLUE_CARDS_SAME_SUIT = 'CLUE CARDS SAME SUIT';
export const HINT_CLUE_CARDS_NOT_SAME_SUIT = 'CLUE CARDS NOT SAME SUIT';
export const HINT_CLUE_RED_SUIT = 'CLUE RED SUIT';
export const HINT_CLUE_BLACK_SUIT = 'CLUE BLACK SUIT';
export const HINT_CLUE_CARD_EVEN = 'CLUE CARD EVEN';
export const HINT_CLUE_CARD_ODD = 'CLUE CARD ODD';
export const HINT_PAIR_NUMBERS_RESTRICTED_BY_SUIT = 'PAIR NUMBERS RESTRICTED BY SUIT';
export const HINT_THREE_OF_A_KIND_NUMBERS_RESTRICTED_BY_SUIT = 'THREE OF A KIND NUMBERS RESTRICTED BY SUIT';
export const HINT_THREE_OF_A_KIND_NUMBERS_ALL_SAME_SUIT = 'THREE OF A KIND NUMBERS ALL SAME SUIT';
export const HINT_PAIR_NUMBERS_ALL_SAME_SUIT = 'PAIR NUMBERS ALL SAME SUIT';
export const HINT_THREE_OF_A_KIND_NUMBERS_NUMBER_NOT_IN_ALL = 'THREE OF A KIND NUMBERS NUMBER NOT IN ALL';
export const HINT_PAIR_NUMBERS_NUMBER_NOT_IN_ALL = 'PAIR NUMBERS NUMBER NOT IN ALL';
export const HINT_ALL_SUITS_OF_NUMBER_NOT_POSSIBLE = 'ALL SUITS OF NUMBER NOT POSSIBLE';
export const HINT_ALL_NUMBERS_OF_SUIT_NOT_POSSIBLE = 'ALL NUMBERS OF SUIT NOT POSSIBLE';
export const HINT_FLUSH_SUIT = 'FLUSH SUIT';
export const HINT_FLUSH_POSSIBLE_SUITS = 'FLUSH POSSIBLE SUITS';
export const HINT_SORT_RULE_NUMBERS = 'SORT RULE NUMBERS';
export const HINT_ALL_SUIT_PLACED_ONLY_PLACE_FOR_NUMBER = 'ALL SUIT PLACED ONLY PLACE FOR NUMBER';

export const ALL_HINTS = [
  HINT_NUMBER_NOT_USED,
  HINT_STRAIGHT_NUMBER_KNOWN,
  HINT_NO_STRAIGHT_FLUSH_IN_SUIT,
  HINT_NO_STRAIGHT_FLUSH_IN_NUMBER,
  HINT_NO_STRAIGHT_IN_NUMBER,
  HINT_SAME_COUNT_LEFT_SUIT,
  HINT_SAME_COUNT_LEFT_NUMBER,
  HINT_FOUR_OF_A_KIND_SUIT,
  HINT_FOUR_OF_A_KIND_NUMBERS,
  HINT_PLACED_CARD_REMOVE_SUIT,
  HINT_PLACED_CARD_REMOVE_NUMBER,
  HINT_NUMBER_USED_UP,
  HINT_ALL_OF_SUIT_PLACED,
  HINT_ALL_OF_SUIT_PLACED_NUMBERS,
  HINT_ALL_OF_NUMBER_PLACED,
  HINT_ALL_OF_NUMBER_PLACED_SUITS,
  HINT_THREE_OF_A_KIND_NUMBERS,
  HINT_THREE_OF_A_KIND_SUITS,
  HINT_PAIR_NUMBERS,
  HINT_PAIR_SUITS,
  HINT_CLUE_SUIT_AND_NUMBER,
  HINT_CLUE_SUIT,
  HINT_CLUE_NOT_SUIT,
  HINT_CLUE_NUMBER,
  HINT_CLUE_NOT_NUMBER,
  HINT_CLUE_CARDS_SAME_NUMBER,
  HINT_CLUE_CARDS_NOT_SAME_NUMBER,
  HINT_CLUE_CARDS_SAME_SUIT,
  HINT_CLUE_CARDS_NOT_SAME_SUIT,
  HINT_CLUE_RED_SUIT,
  HINT_CLUE_BLACK_SUIT,
  HINT_CLUE_CARD_EVEN,
  HINT_CLUE_CARD_ODD,
  HINT_PAIR_NUMBERS_RESTRICTED_BY_SUIT,
  HINT_THREE_OF_A_KIND_NUMBERS_RESTRICTED_BY_SUIT,
  HINT_THREE_OF_A_KIND_NUMBERS_ALL_SAME_SUIT,
  HINT_PAIR_NUMBERS_ALL_SAME_SUIT,
  HINT_THREE_OF_A_KIND_NUMBERS_NUMBER_NOT_IN_ALL,
  HINT_PAIR_NUMBERS_NUMBER_NOT_IN_ALL,
  HINT_ALL_SUITS_OF_NUMBER_NOT_POSSIBLE,
  HINT_ALL_NUMBERS_OF_SUIT_NOT_POSSIBLE,
  HINT_FLUSH_SUIT,
  HINT_FLUSH_POSSIBLE_SUITS,
  HINT_SORT_RULE_NUMBERS,
  HINT_ALL_SUIT_PLACED_ONLY_PLACE_FOR_NUMBER,
];

export const CLUE_HAND_OF_TYPE = 'HAND OF TYPE';
export const CLUE_SUIT_AND_NUMBER = 'SUIT AND NUMBER';
export const CLUE_SUIT = 'SUIT';
export const CLUE_NOT_SUIT = 'NOT SUIT';
export const CLUE_NUMBER = 'NUMBER';
export const CLUE_NOT_NUMBER = 'NOT NUMBER';
export const CLUE_CARDS_SAME_NUMBER = 'CARDS SAME NUMBER';
export const CLUE_CARDS_NOT_SAME_NUMBER = 'CARDS NOT SAME NUMBER';
export const CLUE_CARDS_SAME_SUIT = 'CARDS SAME SUIT';
export const CLUE_CARDS_NOT_SAME_SUIT = 'CARDS NOT SAME SUIT';
export const CLUE_RED_SUIT = 'RED SUIT';
export const CLUE_BLACK_SUIT = 'BLACK SUIT';
export const CLUE_RED_SUITS = 'RED SUITS';
export const CLUE_BLACK_SUITS = 'BLACK SUITS';
export const CLUE_CARD_EVEN = 'CARD EVEN';
export const CLUE_CARD_ODD = 'CARD ODD';
export const CLUE_ALL_CARDS_EVEN = 'ALL CARDS EVEN';
export const CLUE_ALL_CARDS_ODD = 'ALL CARDS ODD';
export const CLUE_ALL_CARDS_NOT_NUMBER = 'ALL CARDS NOT NUMBER';
export const CLUE_ALL_CARDS_NOT_SUIT = 'ALL CARDS NOT SUIT';

// order of clues for sorting
export const CLUE_ORDERING = {
  [CLUE_HAND_OF_TYPE]: 100,

  [CLUE_SUIT_AND_NUMBER]: 90,

  [CLUE_SUIT]: 80,
  [CLUE_NOT_SUIT]: 79,
  [CLUE_ALL_CARDS_NOT_SUIT]: 78,
  [CLUE_RED_SUIT]: 77,
  [CLUE_RED_SUITS]: 76,
  [CLUE_BLACK_SUIT]: 75,
  [CLUE_BLACK_SUITS]: 74,

  [CLUE_NUMBER]: 70,
  [CLUE_NOT_NUMBER]: 69,
  [CLUE_ALL_CARDS_NOT_NUMBER]: 68,
  [CLUE_CARD_EVEN]: 67,
  [CLUE_ALL_CARDS_EVEN]: 66,
  [CLUE_CARD_ODD]: 65,
  [CLUE_ALL_CARDS_ODD]: 64,

  [CLUE_CARDS_SAME_SUIT]: 60,
  [CLUE_CARDS_NOT_SAME_SUIT]: 59,

  [CLUE_CARDS_SAME_NUMBER]: 50,
  [CLUE_CARDS_NOT_SAME_NUMBER]: 49,
};

// order of clues for reducing the clues
export const CLUE_ORDERING_REDUCING = {
  [CLUE_SUIT_AND_NUMBER]: 100,

  [CLUE_SUIT]: 90,
  [CLUE_NUMBER]: 89,

  [CLUE_RED_SUIT]: 80,
  [CLUE_BLACK_SUIT]: 79,

  [CLUE_CARD_EVEN]: 70,
  [CLUE_CARD_ODD]: 69,

  [CLUE_RED_SUITS]: 60,
  [CLUE_BLACK_SUITS]: 59,

  [CLUE_ALL_CARDS_EVEN]: 50,
  [CLUE_ALL_CARDS_ODD]: 49,

  [CLUE_NOT_SUIT]: 40,
  [CLUE_NOT_NUMBER]: 39,
  [CLUE_ALL_CARDS_NOT_SUIT]: 38,
  [CLUE_ALL_CARDS_NOT_NUMBER]: 37,

  [CLUE_CARDS_SAME_SUIT]: 30,
  [CLUE_CARDS_NOT_SAME_SUIT]: 29,

  [CLUE_CARDS_SAME_NUMBER]: 20,
  [CLUE_CARDS_NOT_SAME_NUMBER]: 19,

  [CLUE_HAND_OF_TYPE]: 10,
};
